import { BikeInsurance } from "@/types";

export const featureOptions = [
  {label: 'LED Lights', value: 'LED Lights'},
  {label: 'Evolution V-twin Engine', value: 'Evolution V-twin Engine'},
  {label: 'Black Turn Signal Light Covers', value: 'Black Turn Signal Light Covers'},
  {label: 'Dynojet Power Commander V', value: 'Dynojet Power Commander V'},
  {label: 'Single Speed (Automatic) Transmission', value: 'Single Speed (Automatic) Transmission'},
  {label: 'D & D High Performance Exhaust System', value: 'D & D High Performance Exhaust System'},
  {label: 'Chrome Accents', value: 'Chrome Accents'},
  {label: 'High-Performance Exhaust System', value: 'High-Performance Exhaust System'},
  {label: 'Stereo Sound System with Bluetooth', value: 'Stereo Sound System with Bluetooth'},
  {label: 'Fog Lights', value: 'Fog Lights'},
  {label: 'Tail Bag/Box', value: 'Tail Bag/Box'},
  {label: 'USB Charging', value: 'USB Charging'},
  {label: 'Heated Handgrips', value: 'Heated Handgrips'},
  {label: 'Heated Seat', value: 'Heated Seat'},
  {label: 'GPS Navigation', value: 'GPS Navigation'},
  {label: 'K&N High Flow Air Intake', value: 'K&N High Flow Air Intake'},
  {label: 'Stereo Sound System with Bluetooth', value: 'Stereo Sound System with Bluetooth'},
  {label: 'Saddle Bag/Box', value: 'Saddle Bag/Box'},
  {label: 'Storage Compartments', value: 'Storage Compartments'},
  {label: 'Vance & Hines Exhaust System', value: 'Vance & Hines Exhaust System'},
  {label: 'Twin Cam 103 Engine', value: 'Twin Cam 103 Engine'},
  {label: 'Dyno Tuned Engine', value: 'Dyno Tuned Engine'},
  {label: 'GP Series Akrapovic Exhaust System', value: 'GP Series Akrapovic Exhaust System'},
  {label: 'Frame Sliders', value: 'Frame Sliders'},
  {label: 'Integrated Rear Lights', value: 'Integrated Rear Lights'},
  {label: 'Knee Grip Pads', value: 'Knee Grip Pads'},
  {label: 'Low Profile Mirrors', value: 'Low Profile Mirrors'},
  {label: 'Adjustable Clutch Levers', value: 'Adjustable Clutch Levers'},
  {label: 'Adjustable Brake Levers', value: 'Adjustable Brake Levers'},
  {label: 'Touchscreen Boom!™ Box 6.5 GT Bluetooth Audio System', value: 'Touchscreen Boom!™ Box 6.5 GT Bluetooth Audio System'},
  {label: 'Reflex™ Linked Brakes with ABS', value: 'Reflex™ Linked Brakes with ABS'},
  {label: 'Saddlebag Guard For More Passenger Leg Room', value: 'Saddlebag Guard For More Passenger Leg Room'},
  {label: 'Low Profile Front Fender', value: 'Low Profile Front Fender'},
  {label: 'ABS Braking System', value: 'ABS Braking System'},
  {label: 'Akrapovic Full Exhaust System', value: 'Akrapovic Full Exhaust System'},
  {label: 'Liquid-cooled Revolution 60-degree V-twin', value: 'Liquid-cooled Revolution 60-degree V-twin'},
  {label: 'Screaming Eagle Performance Package', value: 'Screaming Eagle Performance Package'},
  {label: 'Stereo Sound System with Radio', value: 'Stereo Sound System with Radio'},
  {label: 'Twin Cam V-Twin Engine', value: 'Twin Cam V-Twin Engine'},
  {label: 'Hydraulic Clutch Actuation', value: 'Hydraulic Clutch Actuation'},
  {label: 'Milwaukee-Eight 114 Engine', value: 'Milwaukee-Eight 114 Engine'},
]

export const highlightOptions = [
  { label: 'Scooter', value: 'Scooter' },
  { label: 'Distance to Refuel 110 Miles', value: 'Distance to Refuel 110 Miles' },
  { label: '49cc', value: '49cc' },
  { label: 'Seat Height 28.9 in.', value: 'Seat Height 28.9 in.' },
  { label: 'Rider & Passenger Weight Limit: 220 lbs.', value: 'Rider & Passenger Weight Limit: 220 lbs.' },
  { label: 'Distance to Refuel 200 Miles', value: 'Distance to Refuel 200 Miles' },
  { label: 'Seat Height 31.70 in.', value: 'Seat Height 31.70 in.' },
  { label: '1300cc', value: '1300cc' },
  { label: 'Sport Bike', value: 'Sport Bike' },
  { label: 'Rider & Passenger Weight Limit: 430 lbs.', value: 'Rider & Passenger Weight Limit: 430 lbs.' },
  { label: 'Street Motorcycle', value: 'Street Motorcycle' },
  { label: '883cc', value: '883cc' },
  { label: 'Seat Height 28 in.', value: 'Seat Height 28 in.' },
  { label: 'Touring Motorcycle', value: 'Touring Motorcycle' },
  { label: 'Seat Height 26.5 in.', value: 'Seat Height 26.5 in.' },
  { label: 'Distance to Refuel 230 Miles', value: 'Distance to Refuel 230 Miles' },
  { label: 'Rider & Passenger Weight Limit: 507 lbs.', value: 'Rider & Passenger Weight Limit: 507 lbs.' },
  { label: '6 Speed Transmission', value: '6 Speed Transmission' },
  { label: '111ci (1819cc)', value: '111ci (1819cc)' },
  { label: '250cc', value: '250cc' },
  { label: 'Distance to Refuel 240 Miles', value: 'Distance to Refuel 240 Miles' },
  { label: 'Seat Height 30.3 in.', value: 'Seat Height 30.3 in. ' },
  { label: 'Rider & Passenger Weight Limit: 454 lbs.', value: 'Rider & Passenger Weight Limit: 454 lbs.' },
  { label: '1200cc', value: '1200cc' },
  { label: 'Distance to Refuel 145 Miles', value: 'Distance to Refuel 145 Miles' },
  { label: 'Seat Height 28.3 in.', value: 'Seat Height 28.3 in.' },
  { label: 'Rider & Passenger Weight Limit: 409 lbs', value: 'Rider & Passenger Weight Limit: 409 lbs' },
  { label: 'Rider & Passenger Weight Limit: 436 lbs.', value: 'Rider & Passenger Weight Limit: 436 lbs.' },
  { label: 'Distance to Refuel 150 Miles', value: 'Distance to Refuel 150 Miles' },
  { label: 'Rider & Passenger Weight Limit: 320 lbs.', value: 'Rider & Passenger Weight Limit: 320 lbs.' },
  { label: 'Seat Height 31 in.', value: 'Seat Height 31 in.' },
  { label: 'Distance to Refuel 120 Miles', value: 'Distance to Refuel 120 Miles' },
  { label: 'Distance to Refuel 207', value: 'Distance to Refuel 207' },
  { label: 'Rider & Passenger Weight Limit: 409 lbs.', value: 'Rider & Passenger Weight Limit: 409 lbs.' },
  { label: '1690cc', value: '1690cc' },
  { label: 'Distance to Refuel 252 Miles', value: 'Distance to Refuel 252 Miles' },
  { label: 'Seat Height 26 in.', value: 'Seat Height 26 in.' },
  { label: 'Rider & Passenger Weight Limit: 530 lbs.', value: 'Rider & Passenger Weight Limit: 530 lbs.' },
  { label: 'Distance to Refuel 90 Miles', value: 'Distance to Refuel 90 Miles' },
  { label: '1584cc', value: '1584cc' },
  { label: 'Seat Height 27.3 in.', value: 'Seat Height 27.3 in.' },
  { label: 'Rider & Passenger Weight Limit: 536 lbs.', value: 'Rider & Passenger Weight Limit: 536 lbs.' },
  { label: 'Rider & Passenger Weight Limit: 200 lbs.', value: 'Rider & Passenger Weight Limit: 200 lbs.' },
  { label: '310cc', value: '310cc' },
  { label: 'Rider & Passenger Weight Limit: 412 lbs.', value: 'Rider & Passenger Weight Limit: 412 lbs.' },
  { label: 'Seat Height 30.9 in.', value: 'Seat Height 30.9 in.' },
  { label: '750cc', value: '750cc' },
  { label: 'Distance to Refuel 220 Miles', value: 'Distance to Refuel 220 Miles' },
  { label: 'Seat Height 32.1 in.', value: 'Seat Height 32.1 in.' },
  { label: '321cc', value: '321cc' },
  { label: 'Rider & Passenger Weight Limit: 353 lbs.', value: 'Rider & Passenger Weight Limit: 353 lbs.' },
  { label: '103ci (1688cc)', value: '103ci (1688cc)' },
  { label: '1250cc', value: '1250cc' },
  { label: 'Distance to Refuel 185 Miles', value: 'Distance to Refuel 185 Miles' },
  { label: 'Rider & Passenger Weight Limit: 398 lbs.', value: 'Rider & Passenger Weight Limit: 398 lbs.' },
  { label: '96ci (1584cc)"', value: '96ci (1584cc)"' },
  { label: 'Bluetooth Audio System', value: 'Bluetooth Audio System' },
  { label: 'GPS Navigation', value: 'GPS Navigation' },
  { label: '114ci (1868cc)', value: '114ci (1868cc)' },
]

export const extraOptions = [
  { label: 'Phone Mount Rental + $5.00 / Day', value: 'Phone Mount Rental + $5.00 / Day' },
  { label: 'Half Helmet Rental + $15.00 / Day', value: 'Half Helmet Rental + $15.00 / Day' },
  { label: 'Full Face Helmet + $15.00 / Day', value: 'Full Face Helmet + $15.00 / Day' },
  { label: 'Premium Leather Motorcycle Gloves + $5.00 / Day"', value: 'Premium Leather Motorcycle Gloves + $5.00 / Day"' },
  { label: 'Premium Leather Jacket + $25.00 / Day', value: 'Premium Leather Jacket + $25.00 / Day' },
  { label: 'Passenger Seat Rental + $10.00 / Day', value: 'Passenger Seat Rental + $10.00 / Day' },
  { label: 'Premium Leather Motorcycle Gloves + $5.00 / Day', value: 'Premium Leather Motorcycle Gloves + $5.00 / Day' },
  { label: 'Premium Leather Jacket + $25.00 / Day', value: 'Premium Leather Jacket + $25.00 / Day' },
]

export const initInsurances: BikeInsurance[] = [
  {
    dailyRate: 2800,
    deposit: 130000,
    description: '${deposit} max out-of-pocket cost for motorcycle damages',
    id: 1,
    maxAge: 25,
    minAge: 21,
    popUpDescription: 'A temporary hold for ${deposit} will be placed on your card to confirm funds availability in case of damage (insurance deductible)',
    type: 'minimum',
  },
  {
    dailyRate: 2400,
    deposit: 110000,
    description: '${deposit} max out-of-pocket cost for motorcycle damages',
    id: 2,
    maxAge: 35,
    minAge: 26,
    popUpDescription: 'A temporary hold for ${deposit} will be placed on your card to confirm funds availability in case of damage (insurance deductible)',
    type: 'minimum',
  },
  {
    dailyRate: 2000,
    deposit: 80000,
    description: '${deposit} max out-of-pocket cost for motorcycle damages',
    id: 3,
    maxAge: 999,
    minAge: 36,
    popUpDescription: 'A temporary hold for ${deposit} will be placed on your card to confirm funds availability in case of damage (insurance deductible)',
    type: 'minimum',
  },

  {
    dailyRate: 3400,
    deposit: 100000,
    description: '${deposit} max out-of-pocket cost for motorcycle damages',
    id: 4,
    maxAge: 25,
    minAge: 21,
    popUpDescription: 'A temporary hold for ${deposit} will be placed on your card to confirm funds availability in case of damage (insurance deductible)',
    type: 'standard',
  },
  {
    dailyRate: 3000,
    deposit: 80000,
    description: '${deposit} max out-of-pocket cost for motorcycle damages',
    id: 5,
    maxAge: 35,
    minAge: 26,
    popUpDescription: 'A temporary hold for ${deposit} will be placed on your card to confirm funds availability in case of damage (insurance deductible)',
    type: 'standard',
  },
  {
    dailyRate: 2600,
    deposit: 50000,
    description: '${deposit} max out-of-pocket cost for motorcycle damages',
    id: 6,
    maxAge: 999,
    minAge: 36,
    popUpDescription: 'A temporary hold for ${deposit} will be placed on your card to confirm funds availability in case of damage (insurance deductible)',
    type: 'standard',
  },

  {
    dailyRate: 4200,
    deposit: 60000,
    description: '${deposit} max out-of-pocket cost for motorcycle damages',
    id: 7,
    maxAge: 25,
    minAge: 21,
    popUpDescription: 'A temporary hold for ${deposit} will be placed on your card to confirm funds availability in case of damage (insurance deductible)',
    type: 'premium',
  },
  {
    dailyRate: 3800,
    deposit: 50000,
    description: '${deposit} max out-of-pocket cost for motorcycle damages',
    id: 8,
    maxAge: 35,
    minAge: 26,
    popUpDescription: 'A temporary hold for ${deposit} will be placed on your card to confirm funds availability in case of damage (insurance deductible)',
    type: 'premium',
  },
  {
    dailyRate: 3400,
    deposit: 30000,
    description: '${deposit} max out-of-pocket cost for motorcycle damages',
    id: 9,
    maxAge: 999,
    minAge: 36,
    popUpDescription: 'A temporary hold for ${deposit} will be placed on your card to confirm funds availability in case of damage (insurance deductible)',
    type: 'premium',
  }
];

export const initBikeData = {
  bike: {
    name: '',
    slug: '', 
    featuredMediaItemId: null,
    featuredMediaItem: null,
    description: '',
    typeId: null,
    brandId: null,
    model: '',
    regularPrice: null,
    discountPrice: 0, // will remove
    twoDaysDiscount: 5,
    threeDaysDiscount: 8,
    fourDaysDiscount: 12,
    fiveDaysDiscount: 20,
    distanceIncluded: '',
    highlights: null,
    features: null,
    extras: null,
    status: '',
    position: null
  },
  galleryImageIds: null,
  galleryMediaItems: [],
  offDays: [],
  basePrices: [],
  insurancePlans: initInsurances,
  relatedBikes: []
};